constants:
  file:
    directory: /home/download   # ??? ??

  open-feign:
    user: mujiuniv-user #유저 서버 이름

spring:
  application:
    name: mujiuniv-function

  datasource:
    # log4jdbc ?? ???? DriverSpy + jdbc:log4jdbc: ?? ??
    url: jdbc:log4jdbc:mariadb://112.222.157.157:5013/final_project_not_user?useUnicode=true&characterEncoding=UTF-8

    username: green3
    password: figma502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000     # 5분
      max-lifetime: 1800000    # 30분
      connection-timeout: 30000

  jpa:
    database: mysql
    defer-datasource-initialization: true # 중요. JPA 테이블 생성 이후 data.sql
    hibernate:
      #  ddl-auto: update #데이블은 없는데 entity가 존재하면 create 한다.
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        format_sql: true # 쿼리문 로그를 찍어줄 때 보기 편하게 포맷팅
        order_updates: true
        show_sql: true

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    default-statement-timeout: 10
  # resources ?? ?? classpath ???? ???? ?? ??
  mapper-locations: classpath:/mappers/**/*.xml

mail:
  smtp:
    host: "smtp.gmail.com"
    username: "mujiuniv@gmail.com"
    password: "dqknokdqkusfndls"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000

server:
  port: 8082
  servlet:
    session:
      cookie:
        same-site: lax   # Lax / Strict / None
        path: /          # ??? /
        # domain: localhost  # ??? ?? ??? ?? ??? ? ??

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: INFO
    # ??? ??(? ???? ?????? ??)
    com.rainbowuniv: DEBUG
    org.mybatis: DEBUG
    # log4jdbc ????
    jdbc.sqlonly: DEBUG     # ??? SQL
    jdbc.sqltiming: INFO    # ???? ??
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.connection: OFF